### ISSUE TITLE
可以通过代理发送短信么

### ISSUE THREAD

**Issue by sunshineboyle** [pkg6/go-sms#1]

**Comment by chihqiang** [comment]
你的意思是用socket5等代理的方式进行接口请求吗

**Comment by sunshineboyle** [comment]
对的




柳乐
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pkg6/go-sms"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月23日(星期六) 晚上11:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pkg6/go-sms] 可以通过代理发送短信么 (Issue #1)





 
你的意思是用socket5等代理的方式进行接口请求吗

**Comment by chihqiang** [comment]
~~~
package main

import (
	"fmt"
	gosms "github.com/pkg6/go-sms"
	"github.com/pkg6/go-sms/gateways/ihuyi"
)

func main() {
	//设置socket代理
	gosms.Client.WithProxyUrl("socks5://USER:PASSWORD@IP:PORT")
	//设置http代理
	//gosms.Client.WithProxyUrl("http://USER:PASSWORD@IP:PORT")
	var number = gosms.NoCodePhoneNumber(18888888888)
	//对接相关资源 APIID 为account APIKEY 为password
	var gateway = ihuyi.GateWay("APIID", "APIKEY")
	var message = gosms.MessageContent("您的验证码是：****。请不要把验证码泄露给其他人。")
	result, err := gosms.Sender(number, message, gateway)
	if resp, ok := result.ClientResult.Response.(ihuyi.Response); ok {
		fmt.Println(resp)
	}
	fmt.Println(err)
}


~~~
