### ISSUE TITLE
短信包的包中缺少包导入

### ISSUE THREAD

**Issue by github-wutao1993** [pkg6/go-sms#2]

**Comment by github-wutao1993** [comment]
短信宝的包

**Comment by chihqiang** [comment]
短信包参考案例代码：
https://github.com/pkg6/go-sms/blob/229b098b5af8ad7ace2c7566d0b4ed9cf216335b/_example/sender/main.go#L28

执行`go get github.com/pkg6/go-sms `会自动将依赖包安装到最新的版本
